import { createTool } from '@mastra/core/tools';
import { z } from 'zod';

export const musicGenerationTool = createTool({
  id: 'music-generation',
  description: 'Generate musical compositions based on specified parameters like style, mood, tempo, and duration. Returns a structured musical representation.',
  inputSchema: z.object({
    style: z.enum(['classical', 'jazz', 'rock', 'electronic', 'pop', 'hiphop', 'blues', 'country']).describe('Musical style or genre'),
    mood: z.enum(['happy', 'sad', 'energetic', 'calm', 'melancholic', 'exciting', 'romantic', 'dark']).describe('Emotional tone of the composition'),
    tempo: z.number().min(40).max(240).describe('Tempo in BPM (beats per minute)'),
    duration: z.number().min(1).max(60).describe('Duration in minutes'),
    key: z.string().describe('Musical key (e.g., C major, A minor)'),
    instruments: z.array(z.string()).optional().describe('List of instruments to include in the composition'),
  }),
  outputSchema: z.object({
    compositionId: z.string().describe('Unique identifier for the generated composition'),
    title: z.string().describe('Generated title for the composition'),
    style: z.string(),
    mood: z.string(),
    tempo: z.number(),
    duration: z.number(),
    key: z.string(),
    instruments: z.array(z.string()),
    notes: z.array(z.object({
      pitch: z.string().describe('Note pitch (e.g., C4, E#5)'),
      duration: z.number().describe('Note duration in beats'),
      startTime: z.number().describe('Start time in beats from composition beginning'),
      velocity: z.number().min(0).max(127).describe('Note velocity (loudness) 0-127'),
    })).describe('Array of musical notes with timing information'),
    chordProgression: z.array(z.string()).describe('Chord progression used in the composition'),
    metadata: z.object({
      createdAt: z.string().describe('Timestamp when composition was created'),
      version: z.string().describe('Version of the generation algorithm'),
    }),
  }),
  execute: async ({ style, mood, tempo, duration, key, instruments = [] }) => {
    // This is a placeholder implementation that would typically call
    // an actual music generation API or model
    
    // Generate a mock composition for demonstration purposes
    const compositionId = `comp_${Math.random().toString(36).substr(2, 9)}`;
    const title = `${mood.charAt(0).toUpperCase() + mood.slice(1)} ${style} Composition`;
    
    // Mock notes data (would be generated by actual music generation logic)
    const mockNotes = [
      { pitch: 'C4', duration: 1, startTime: 0, velocity: 80 },
      { pitch: 'E4', duration: 1, startTime: 1, velocity: 80 },
      { pitch: 'G4', duration: 1, startTime: 2, velocity: 80 },
      { pitch: 'C5', duration: 2, startTime: 3, velocity: 80 },
    ];
    
    // Mock chord progression
    const mockChordProgression = ['C', 'G', 'Am', 'F'];
    
    return {
      compositionId,
      title,
      style,
      mood,
      tempo,
      duration,
      key,
      instruments,
      notes: mockNotes,
      chordProgression: mockChordProgression,
      metadata: {
        createdAt: new Date().toISOString(),
        version: '1.0.0',
      },
    };
  },
});